version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salesdb
      MYSQL_USER: salesuser
      MYSQL_PASSWORD: salespass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  streamlit:
    build: ./streamlit
    volumes:
      - ./streamlit:/app
    ports:
      - "8501:8501"
    environment:
      - LLAMA_API_URL=http://llama-api:11434
      - MYSQL_HOST=mysql
      - MYSQL_USER=salesuser
      - MYSQL_PASSWORD=salespass
      - MYSQL_DB=salesdb
    depends_on:
      - mysql
