version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salesdb
      MYSQL_USER: salesuser
      MYSQL_PASSWORD: salespass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  streamlit:
    build: ./streamlit
    volumes:
      - ./streamlit:/app
    ports:
      - "8501:8501"
    environment:
      - LM_STUDIO_API_URL=hthttp://host.docker.internal:11434
      - MYSQL_HOST=mysql
      - MYSQL_USER=salesuser
      - MYSQL_PASSWORD=salespass
      - MYSQL_DB=salesdb
      - GEMINI_API_KEY=$GEMINI_API_KEY
    # extra_hosts:
    #   - "host.docker.internal:host-gateway" # For Linux compatibility
    depends_on:
      - mysql
